<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-CIT/blob/main/Python-Libraries/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
some = np.array([1,2,3,4,5])

In [3]:
type(some)

numpy.ndarray

In [4]:
a = np.array([[1,2,3],[4,5,6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = np.arange(10,50,5).reshape(2, 4)
a

array([[10, 15, 20, 25],
       [30, 35, 40, 45]])

In [7]:
b = np.linspace(1,10,5).reshape(5,1)
b

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [9]:
np.ndim(a)

2

In [10]:
b.shape

(5, 1)

In [11]:
# np.ones and np.zeros
a = np.ones((3,3))
b = np.zeros((3,3))
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
new = np.array([1,2,3,4,6], ndmin = 10)
print(new)

[[[[[[[[[[1 2 3 4 6]]]]]]]]]]


In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
arr.shape

(3, 4)

In [14]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [15]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr1 = [1,2,3]
arr2 = [2,3,4]

ar = np.concatenate((arr1,arr2))
ar

array([1, 2, 3, 2, 3, 4])

In [17]:
ar = np.random.random(3)
ar

array([0.77806124, 0.96275443, 0.06469415])

In [18]:
# vstack
# hstack
# dstack

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])